# Configuração do servidor
server:
  port: 8080

# Configuração da aplicação
spring:
  application:
    name: delivery-api
  
  # Configuração do MySQL Database
  datasource:
    url: jdbc:mysql://localhost:3306/deliveryApiDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: J@ck3007
  
  # JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Mude para update em produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

# Configurações do SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true

# Configurações do Spring Boot Actuator (Health Check)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true

# Logging
logging:
  level:
    com.deliverytech.delivery: DEBUG
    org.springframework.web: INFO
    org.springdoc: INFO